### ISSUE TITLE
[FEAT] Code the dashboard for XProfile 

### ISSUE THREAD

**Issue by hellofaizan** [Youth-Icon/xprofile#24]
## Tech Stack
<p align="left">
  <a href="https://discord.gg/vUHMxPvege">
    <img src="https://skillicons.dev/icons?i=next,typescript,firebase,tailwind" />
  </a>
</p>

## TODO
- A dashboard that shows the stats of user profile
- Dashboard where user can edit his profile
- Dashboard where user can delete his account

## UI guide
![95f7fbbc-9d65-475c-a036-ddfc57e9c70b](https://github.com/Youth-Icon/xprofile/assets/84437051/c2c8848b-4fc0-4baa-b511-d7d822c98047)

## Join Discord and start working on it
<a href="https://discord.gg/vUHMxPvege">
     <img src="https://invidget.switchblade.xyz/vUHMxPvege" width="398" height="100" />
</a>

**Comment by hellofaizan** [comment]
Ask for assigning the issue first, before starting code on it.

**Comment by Codensity30** [comment]
please change the logo of your website cause this is quite the same as Twitter (X) one

**Comment by hellofaizan** [comment]
We got a new logo for the project. The logo of Twitter was just for preview @Codensity30

**Comment by Codensity30** [comment]
By the way, I can help with the dashboard cause I know TailwindCSS and React.js but not actually Next.

**Comment by hellofaizan** [comment]
Next js has a different way of routing. I think that will be a mess if you start the development without prior knowledge of Next JS @Codensity30 

You should watch a quick Next JS YouTube video or read the docs

**Comment by hellofaizan** [comment]
@Codensity30 Watch a quick video of Next Js 13 and tell me if you comfortable with it or not

**Comment by Codensity30** [comment]
what if I serve the components and you can integrate them, also I can help design the line chart cause in one of my projects I've used Recharts.
would you recommend some?
By the way, if you want your repo to get more attention just add the tag of "hacktoberfest" and "hacktoberfest-accepted" labels on the issue.

**Comment by hellofaizan** [comment]
If that is the case, I would have coded the entire dashboard on my own, but the issue is I have to attend an important exam next month. For the preparation I have paused writing code lines @Codensity30

**Comment by Sarveshk76** [comment]
I would like to work on this issue

**Comment by hellofaizan** [comment]
Awesome. Let's connect on Discord

**Comment by hellofaizan** [comment]
@Sarveshk76 have you joined the Youth Icon Discord to discuss about the issue

Join now
https://discord.gg/vUHMxPvege

**Comment by Sarveshk76** [comment]
Yes, I have joined

**Comment by hellofaizan** [comment]
Your Discord tag??

**Comment by Bashamega** [comment]
Hello:)
I am coder_master who contacted you I still didn't get assigned

**Comment by hellofaizan** [comment]
Done #56 #53 #54
