### ISSUE TITLE
Correction for Home's content width

### ISSUE THREAD

**Issue by mercuryeater** [Youth-Icon/xprofile#27]
Hey, I would like to make a small contribution to the project by improving the Desktop appearance of the Home route, in big Screens the content its applied to the full width and the legibility is reduced, as you can see even the full image of the profile. 
I would maybe just put a width limit for the XProfile part.
![image](https://github.com/Youth-Icon/xprofile/assets/79395978/2e6d1a51-9ab8-4622-9121-ce51c4bd51d5)

**Comment by hellofaizan** [comment]
Go for it. Assigning you the issue @mercuryeater

**Comment by mercuryeater** [comment]
Sorry, @hellofaizan I just forked the repository and I've been looking for the home component but I haven't been able to find it, inside the "/" route it's only the "Under construction🚧" button, am I in the wrong repo or something?
Also just after install I'm having all this hydration errors, alongside something with the naming of properties, I suppose something wrong with the bundler?

Hydration failed:
![image](https://github.com/Youth-Icon/xprofile/assets/79395978/d8cb3a96-fe8f-4105-a3ea-df15e4c62684)

Bundle errors:
![image](https://github.com/Youth-Icon/xprofile/assets/79395978/044b7a3d-d69e-4afd-a30c-377acb0e5490)

**Comment by hellofaizan** [comment]
@mercuryeater you forked the wrong branch. The `main` branch, we kept that untouched. We are working on `dev` branch, fork that
