### ISSUE TITLE
[FEAT] Explore page improvement. 

### ISSUE THREAD

**Issue by Bashamega** [Youth-Icon/xprofile#39]
Hello:)
The [Explore page](https://xprofile-git-dev-youthicon.vercel.app/explore) doesn't have good ui. Also when you click on view profile it takes you to `https://xprofile-git-dev-youthicon.vercel.app/user/{username}`.

I have made a design better for it
![image](https://github.com/Youth-Icon/xprofile/assets/110662505/53ecbb38-5bf9-4e2a-b1a2-c08545ce7280)
![image](https://github.com/Youth-Icon/xprofile/assets/110662505/39e3c71f-0682-4289-9dd6-7700d75b1121)
I can merge a pr if you want

**Comment by hellofaizan** [comment]
Ok PR

**Comment by Bashamega** [comment]
> Ok PR

Thanks
