### ISSUE TITLE
[Feat] Undefined links

### ISSUE THREAD

**Issue by Bashamega** [Youth-Icon/xprofile#40]
Hello:
I have notices that if you go to a user that didn't link his accounts it shows the icon, and go to just the default url for the website.
![image](https://github.com/Youth-Icon/xprofile/assets/110662505/8ef42f24-2e19-4be4-beeb-28b30740dc59)
It should hide the icons that isn't linked.
I can fix it

**Comment by hellofaizan** [comment]
We fixed it. But old profiles still have it on.
https://github.com/Youth-Icon/xprofile/commit/81b95218fef8095a407a2cdd1986475f25ac1bbe

☝️Have a look @Bashamega

**Comment by Bashamega** [comment]
> We fixed it. But old profiles still have it on. [81b9521](https://github.com/Youth-Icon/xprofile/commit/81b95218fef8095a407a2cdd1986475f25ac1bbe)
> 
> ☝️Have a look @Bashamega

I didn't know
But I think I can do it also for old profiles
