### ISSUE TITLE
[BUG] Footer not Aligned well

### ISSUE THREAD

**Issue by hellofaizan** [Youth-Icon/xprofile#51]
## Live Preview https://xprofile.us

![image](https://github.com/Youth-Icon/xprofile/assets/84437051/6124dce8-8e8f-42fe-8b7f-b81dc024cb9f)

**Comment by Bashamega** [comment]
Hello:) Please assign me

**Comment by hellofaizan** [comment]
Done @Bashamega . Assigned you the issue.
