### ISSUE TITLE
[💄UI] Need a good landing page for XProfile

### ISSUE THREAD

**Issue by hellofaizan** [Youth-Icon/xprofile#8]
## [Repository Link](https://github.com/Youth-Icon/xprofile)

We have been continuously working on Version 2 of XProfile, where we have added a lot of features, new designs. We are looking for someone who can design a good landing page for us.

# TODO:
- Design a modern design landing page for XProfile
- [Join Discord](https://discord.gg/vUHMxPvege). The community will give  suggestions and feedbacks
- Design should be minimal and catchy

**Comment by Anmol-Baranwal** [comment]
I can work on this. But need designs and stuff.

I can also create myself with minimalistic design. Got this from LinksHub :)

**Comment by hellofaizan** [comment]
Oo great @Anmol-Baranwal Thank you for your precious time. We are creating a linktree clone with a lot of more features. Now we need a landing page for it. Design inspiration could be taken from the landing page of https://bento.me/en/home

[Join our Discord](https://discord.gg/vUHMxPvege) to discuss more about it

**Comment by LutherkingCode** [comment]
I think i Can give it a try

**Comment by hellofaizan** [comment]
Great 👍 go for it. @LutherkingCode 

We need a modern design for it. It's just the open source alternative for linktree. Take design inspiration from https://bento.me/en/home and https://linktr.ee/

**Comment by symaticvisuals** [comment]
Hi @hellofaizan , I would be interested in contributing to this issue.

**Comment by hellofaizan** [comment]
It's just the design. You can start code after we finalise the design. We need a design for Landing page first @symaticvisuals • If you are okay with it, you can start

**Comment by symaticvisuals** [comment]
Hey @hellofaizan, I have design skills and would be interested in working together on a landing page. Could you share some ideas for sections you think should be on the page? Once I have some direction, I can start creating a design in Figma.

**Comment by hellofaizan** [comment]
Seeing you a theme on your Discord DM
