### ISSUE TITLE
[Pages]  New pages

### ISSUE THREAD

**Issue by Bashamega** [Youth-Icon/xprofile#86]
We have to create the following pages:

1. About us
2. Explore (static for now)
3. Showcase
4. Social Links
5. Personalization
6. Profile Themes
7. API
8. Community
9. Help center
10. xProfile + Youth Icon
11. Open-source Software
12. Privacy
13. Terms

**Comment by ghousetazeem** [comment]
I would love to work on adding new pages. I can start off by doing work on About us page if I get the requirement mentioned correctly or the design to implement

**Comment by hellofaizan** [comment]
> I would love to work on adding new pages. I can start off by doing work on About us page if I get the requirement mentioned correctly or the design to implement

That's great @ghousetazeem but we don't have a design for it. I advice you to join our discord where we discuss things

**Comment by ghousetazeem** [comment]
Ok sure
