### ISSUE TITLE
Home Page Random Image Bug

### ISSUE THREAD

**Issue by ghousetazeem** [Youth-Icon/xprofile#95]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Production

### Description

As you can see above, that's how that image is popping up while on desktop mode

### Steps to Reproduce

Just simply when I clicked the link form the about section of the repository, I saw it at the very first and thought it would be some UI design, but after seeing the username input behind that image, then realized that's actually a bug that needed to be fixed

### Screenshots

![image](https://github.com/Youth-Icon/xprofile/assets/74200389/06a14a2b-68b4-4006-927d-cbac1b5c62d1)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

First approach would be to just simply delete the image that is causing the problem
Or Second approach would be to see if that image is being used else where or not, in either cases I can fix that by simply displaying none while on screen mode

**Comment by Bashamega** [comment]
Hello:)
I am Adam, a contributor and a part of the team.
I couldn't replicate your bug, but it can be cause of old browser or slow internet.
It is fully working on the main [xprofile website](https://xprofile.us/).
