### ISSUE TITLE
Site URL is not working

### ISSUE THREAD

**Issue by dipanshurdev** [Youth-Icon/xprofile#96]
Url [https://xprofile.us/](https://xprofile.us/) is not working. Showing an Error ``This site can’t be reached``

**Comment by hellofaizan** [comment]
Site is under development, also the domain name got expired 🥲

here is alternative url https://xv2profile.vercel.app/

**Comment by dipanshurdev** [comment]
> Site is under development, also the domain name got expired 🥲
> 
> here is alternative url https://xv2profile.vercel.app/

Ohh 😅
